{
    'name': 'Sulpak Management',
    'version': '1.0.0',
    'category': 'Ecommerce',
    'summary': 'Sulpak Management system',
    'description': """This mod""",
    'depends': ['base', 'portal'],
    'data': [
        'security\ir.model.access.csv',
        'views\menu.xml',
        'views\smartphone_view.xml',
        'views\shop.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3',
    'sequence': -100,
    'application': True,
}
