{
    'name': 'Station Management',
    'version': '1.0.0',
    'category': 'Station',
    'summary': 'Station Management system',
    'description': """This mod""",
    'depends': [],
    'data': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'assets': {},
    'post_init_hook': '_synchronize_cron',
    'license': 'LGPL-3',
    'sequence': -100,
    'application': True,
}
